import { Barlow_Condensed } from "next/font/google";
import "./globals.scss";
import SideBar from "@/components/sidebar/SideBar";

const inter = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  );
}
